services:
  app:
    build:
      context: ../../
      dockerfile: deploy/dev/Dockerfile
    container_name: nestjs_dev
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ../../.:/app
      - ../../node_modules:/app/node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - db
    networks:
      - nest-network
    command: npm run start:dev
    env_file:
      - ../../.env

  postgres:
    image: postgres:17.7-alpine
    container_name: postgres_dev
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nest-network
    env_file:
      - ../../.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - nest-network

volumes:
  postgres_data:

networks:
  nest-network:
    driver: bridge
